Stat svc
KirSkl/java-explore-with-me pull request #3
Opened 2023-10-19 11:55 UTC by KirSkl

2023-10-20 06:55 UTC, LexLippi requested changes
Привет!

Хорошая работа!

Есть пара замечаний, которые необходимо исправить!

2023-10-20 06:55 UTC, LexLippi commented on ewm-stats-service/stats-server/src/main/java/ru/practicum/controller/StatsController.java
> +                                       @RequestParam(required = false) List<String> uris) {
Вместопоследующего тернарника достаточно просто в `defaultValue` написать `""` и будет происходить ровно то, что ты хочешь

2023-10-20 06:55 UTC, LexLippi commented on ewm-stats-service/stats-server/src/main/java/ru/practicum/service/StatsServiceImpl.java
> +                EndpointHit::getUri, Collectors.counting()));
Это можно сразу посчитать, с помощью инструментов СУБД

2023-10-20 06:55 UTC, LexLippi commented on ewm-stats-service/stats-server/src/main/resources/schema.sql
> +    uri        VARCHAR(512)                            NOT NULL,
`uri` может иметь длину до 2000 символов:
https://stackoverflow.com/questions/417142/what-is-the-maximum-length-of-a-url-in-different-browsers

2023-10-20 06:55 UTC, LexLippi commented on ewm-stats-service/stats-server/src/main/resources/schema.sql
> +DROP TABLE IF EXISTS hits; --закомментировать для корректной работы приложения
Забыл?
Или без этого не работает?

2023-10-20 06:55 UTC, LexLippi commented on ewm-stats-service/stats-server/src/main/resources/schema.sql
> +    ip         VARCHAR(16),
Может быть `null`?

2023-10-20 10:56 UTC, KirSkl commented on ewm-stats-service/stats-server/src/main/resources/schema.sql
> +DROP TABLE IF EXISTS hits; --закомментировать для корректной работы приложения
Забыл!

2023-10-21 14:29 UTC, LexLippi commented
Привет!

Отличная работа!

Желаю удачи со следующими этапами диплома!

2023-10-22 16:54 UTC, merged